03:13:26 PM:DEBUG [logger_base.py:16] Mensaje a nivel Debug
03:13:26 PM:INFO [logger_base.py:17] Mensaje a nivel Info
03:13:26 PM:WARNING [logger_base.py:18] Mensaje a nivel Warning
03:13:26 PM:ERROR [logger_base.py:19] Mensaje a nivel de Error
03:13:26 PM:CRITICAL [logger_base.py:20] Mensaje a nivel critical
02:36:22 PM:DEBUG [logger_base.py:16] Mensaje a nivel Debug
02:36:22 PM:INFO [logger_base.py:17] Mensaje a nivel Info
02:36:22 PM:WARNING [logger_base.py:18] Mensaje a nivel Warning
02:36:22 PM:ERROR [logger_base.py:19] Mensaje a nivel de Error
02:36:22 PM:CRITICAL [logger_base.py:20] Mensaje a nivel critical
02:36:57 PM:DEBUG [logger_base.py:16] Mensaje a nivel Debug
02:36:57 PM:INFO [logger_base.py:17] Mensaje a nivel Info
02:36:57 PM:WARNING [logger_base.py:18] Mensaje a nivel Warning
02:36:57 PM:ERROR [logger_base.py:19] Mensaje a nivel de Error
02:36:57 PM:CRITICAL [logger_base.py:20] Mensaje a nivel critical
02:38:12 PM:DEBUG [logger_base.py:16] Mensaje a nivel Debug
02:38:12 PM:INFO [logger_base.py:17] Mensaje a nivel Info
02:38:12 PM:WARNING [logger_base.py:18] Mensaje a nivel Warning
02:38:12 PM:ERROR [logger_base.py:19] Mensaje a nivel de Error
02:38:12 PM:CRITICAL [logger_base.py:20] Mensaje a nivel critical
02:42:21 PM:DEBUG [logger_base.py:16] Mensaje a nivel Debug
02:42:21 PM:INFO [logger_base.py:17] Mensaje a nivel Info
02:42:21 PM:WARNING [logger_base.py:18] Mensaje a nivel Warning
02:42:21 PM:ERROR [logger_base.py:19] Mensaje a nivel de Error
02:42:21 PM:CRITICAL [logger_base.py:20] Mensaje a nivel critical
02:45:03 PM:DEBUG [logger_base.py:16] Mensaje a nivel Debug
02:45:03 PM:INFO [logger_base.py:17] Mensaje a nivel Info
02:45:03 PM:WARNING [logger_base.py:18] Mensaje a nivel Warning
02:45:03 PM:ERROR [logger_base.py:19] Mensaje a nivel de Error
02:45:03 PM:CRITICAL [logger_base.py:20] Mensaje a nivel critical
02:46:21 PM:DEBUG [logger_base.py:16] Mensaje a nivel Debug
02:46:21 PM:INFO [logger_base.py:17] Mensaje a nivel Info
02:46:21 PM:WARNING [logger_base.py:18] Mensaje a nivel Warning
02:46:21 PM:ERROR [logger_base.py:19] Mensaje a nivel de Error
02:46:21 PM:CRITICAL [logger_base.py:20] Mensaje a nivel critical
02:46:34 PM:DEBUG [logger_base.py:16] Mensaje a nivel Debug
02:46:34 PM:INFO [logger_base.py:17] Mensaje a nivel Info
02:46:34 PM:WARNING [logger_base.py:18] Mensaje a nivel Warning
02:46:34 PM:ERROR [logger_base.py:19] Mensaje a nivel de Error
02:46:34 PM:CRITICAL [logger_base.py:20] Mensaje a nivel critical
02:47:22 PM:DEBUG [Persona.py:52] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez, 
            Email: jperez@pmail.com
        
02:49:31 PM:DEBUG [Persona.py:52] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez, 
            Email: jperez@pmail.com
        
02:51:07 PM:DEBUG [Persona.py:52] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez, 
            Email: jperez@pmail.com
        
02:51:07 PM:DEBUG [Persona.py:54] 
            Id Persona: Jose,
            Nombre: Lepez,
            Apellido: ljose@mail.com, 
            Email: None
        
02:51:46 PM:DEBUG [Persona.py:52] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez, 
            Email: jperez@pmail.com
        
02:51:46 PM:DEBUG [Persona.py:54] 
            Id Persona: None,
            Nombre: Jose,
            Apellido: Lepez, 
            Email: ljose@mail.com
        
02:52:50 PM:DEBUG [Persona.py:52] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez, 
            Email: jperez@pmail.com
        
02:52:50 PM:DEBUG [Persona.py:54] 
            Id Persona: None,
            Nombre: Jose,
            Apellido: Lepez, 
            Email: ljose@mail.com
        
02:52:50 PM:DEBUG [Persona.py:56] 
            Id Persona: 1,
            Nombre: None,
            Apellido: None, 
            Email: None
        
05:04:53 PM:DEBUG [connection.py:23] Conexion exitosa: <connection object at 0x000001F94347DCF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
05:06:01 PM:ERROR [connection.py:26] Ocurrio un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgre"

05:06:01 PM:ERROR [connection.py:26] Ocurrio un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgre"

05:06:28 PM:DEBUG [connection.py:23] Conexion exitosa: <connection object at 0x000001BEAB5DDCF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
05:06:58 PM:DEBUG [connection.py:23] Conexion exitosa: <connection object at 0x00000297BC46DCF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
05:06:58 PM:DEBUG [connection.py:36] Se abrio correctamente el cursor: <cursor object at 0x00000297BC400AC0; closed: 0>
02:31:08 PM:DEBUG [Conexion.py:23] Conexion exitosa: <connection object at 0x000002108403DCF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
02:31:08 PM:DEBUG [Conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x0000021083FD0820; closed: 0>
02:40:03 PM:DEBUG [conexion.py:23] Conexion exitosa: <connection object at 0x000001CB5ADEDCF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
02:40:03 PM:DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x000001CB5AD80820; closed: 0>
02:49:22 PM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez, 
            Email: jperez@pmail.com
        
02:49:22 PM:DEBUG [Persona.py:55] 
            Id Persona: None,
            Nombre: Jose,
            Apellido: Lepez, 
            Email: ljose@mail.com
        
02:49:22 PM:DEBUG [Persona.py:57] 
            Id Persona: None,
            Nombre: Jose,
            Apellido: Lepez, 
            Email: ljose@mail.com
        
02:55:33 PM:ERROR [conexion.py:25] Ocurrio un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgre"

02:55:56 PM:DEBUG [conexion.py:22] Conexion exitosa: <connection object at 0x00000152BC8EDCF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
02:55:56 PM:DEBUG [conexion.py:35] Se abrio correctamente el cursor: <cursor object at 0x00000152BC880820; closed: 0>
03:00:05 PM:DEBUG [conexion.py:22] Conexion exitosa: <connection object at 0x000001744CC83010; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
03:00:05 PM:DEBUG [conexion.py:35] Se abrio correctamente el cursor: <cursor object at 0x000001744D10BBC0; closed: 0>
03:00:05 PM:DEBUG [persona_dao.py:36] 
            Id Persona: 1,
            Nombre: Juan Carlos,
            Apellido: Roldan, 
            Email: jcroldan@mail.com
        
03:00:05 PM:DEBUG [persona_dao.py:36] 
            Id Persona: 16,
            Nombre: Carlos,
            Apellido: Lara, 
            Email: clara@mail.com
        
03:00:05 PM:DEBUG [persona_dao.py:36] 
            Id Persona: 17,
            Nombre: Marcos,
            Apellido: Canto, 
            Email: mcanto@mail.com
        
03:00:05 PM:DEBUG [persona_dao.py:36] 
            Id Persona: 18,
            Nombre: Marcelo,
            Apellido: Cuenca, 
            Email: cuencam@mail.com
        
03:00:05 PM:DEBUG [persona_dao.py:36] 
            Id Persona: 20,
            Nombre: Maria,
            Apellido: Esparza, 
            Email: mesparza@mail.com
        
03:00:05 PM:DEBUG [persona_dao.py:36] 
            Id Persona: 22,
            Nombre: Carlos,
            Apellido: Lara, 
            Email: clara@mail.com
        
03:00:05 PM:DEBUG [persona_dao.py:36] 
            Id Persona: 23,
            Nombre: Jorge,
            Apellido: Prol, 
            Email: jprol@mail.com
        
03:00:05 PM:DEBUG [persona_dao.py:36] 
            Id Persona: 24,
            Nombre: Alex,
            Apellido: Rojas, 
            Email: arojas@mail.com
        
